AWSTemplateFormatVersion: '2010-09-09'
Description: Secure Web App - Monitoring (SNS + CloudWatch Alarms)

Parameters:
  ProjectName:
    Type: String
  NotificationEmail:
    Type: String
    Description: Email to subscribe to SNS (you must confirm the email)
  InstanceId:
    Type: String
  AlbFullName:
    Type: String
    Description: From ALB output LoadBalancerFullName (e.g., app/my-alb/abc123)
  TargetGroupFullName:
    Type: String
    Description: From ALB output TargetGroupFullName (e.g., targetgroup/my-tg/abc123)

Resources:
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectName}-alerts"
      Tags:
        - { Key: Project, Value: !Ref ProjectName }
        - { Key: Env, Value: dev }

  AlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertsTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  HighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-ec2-HighCPU"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      AlarmActions: [ !Ref AlertsTopic ]
      OKActions: [ !Ref AlertsTopic ]

  AlbElb5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-alb-ELB-5xx"
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions: [ !Ref AlertsTopic ]
      OKActions: [ !Ref AlertsTopic ]

  AlbTarget5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-alb-Target-5xx"
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
        - Name: TargetGroup
          Value: !Ref TargetGroupFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions: [ !Ref AlertsTopic ]
      OKActions: [ !Ref AlertsTopic ]

Outputs:
  AlertsTopicArn:
    Value: !Ref AlertsTopic
