name: ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

# Minimal global perms
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
  ROLE_ARN: arn:aws:iam::017820667577:role/github-actions-deployer
  ARTIFACT_BUCKET: secure-webapp-artifacts-eu-west-1
  APP_DIR: app
  ZIP_NAME: app-${{ github.sha }}.zip
  VPC_TEMPLATE: iac/vpc_nonat.yaml
  COMPUTE_TEMPLATE: iac/compute_nonat.yaml

# prevent overlapping deploys to main
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------- IAC scan (trusted pushes and same-repo PRs) ----------
  iac-scan:
    name: iac-scan
    runs-on: ubuntu-latest
    # Only run with SARIF upload when event is trusted
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name == github.repository)
permissions:
      contents: read
      security-events: write   # needed for SARIF upload
      actions: read            # lets upload-sarif resolve run metadata
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov (CloudFormation in iac/)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac
          framework: cloudformation
          # TEMP: skip alternate templates you’re not using today
          skip_path: iac/vpc.yaml,iac/compute.yaml
          quiet: true
          soft_fail: false
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload SARIF to GitHub code scanning (non-blocking)
        if: always()                          
        continue-on-error: true               # DO NOT fail the job if code scanning is disabled
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif/results_sarif.sarif

  # ---------- IAC scan (fork PRs – no writes/secrets) ----------
  iac-scan-fork:
    name: iac-scan (fork-safe)
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    permissions:
      contents: read           # NO security-events write on forks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov (read-only, no SARIF upload)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac
          framework: cloudformation
          skip_path: iac/vpc.yaml,iac/compute.yaml
          quiet: true
          soft_fail: false     # still fail PR if there are issues
          output_format: cli

  # ---------- Build, test, and deploy (trusted only) ----------
  build-test-deploy:
    name: build-test-deploy
    runs-on: ubuntu-latest
    needs: [ iac-scan ]   # don’t proceed unless trusted scan passed
    # Only deploy on trusted events (push to main or manual dispatch)
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      id-token: write       # for OIDC → AWS
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      - name: Lint (flake8)
        run: flake8 $APP_DIR

      - name: Lint (black)
        run: black --check $APP_DIR

      - name: Run tests
        run: pytest -q || (echo "No tests yet."; exit 0)

      - name: Package app
        run: |
          mkdir -p dist
          # If your requirements.txt lives under app/, this is correct:
          zip -r "dist/${ZIP_NAME}" "$APP_DIR" app/requirements.txt scripts/ssm_deploy.sh

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload artifact to S3
        run: aws s3 cp "dist/${ZIP_NAME}" "s3://${ARTIFACT_BUCKET}/releases/${ZIP_NAME}"

      - name: Find instance IDs by tag (Project=secure-webapp)
        id: discover
        run: |
          IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Project,Values=secure-webapp" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" --output text)
          echo "ids=${IDS}" >> $GITHUB_OUTPUT

      - name: Deploy via SSM
        if: steps.discover.outputs.ids != ''
        run: |
          read -r -a INSTANCES <<< "${{ steps.discover.outputs.ids }}"
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Secure webapp deploy $GITHUB_SHA" \
            --instance-ids "${INSTANCES[@]}" \
            --parameters commands='[
              "set -euo pipefail",
              "mkdir -p /opt/app",
              "aws s3 cp s3://${{ env.ARTIFACT_BUCKET }}/releases/${{ env.ZIP_NAME }} /opt/app/app.zip",
              "unzip -o /opt/app/app.zip -d /opt/app",
              "chmod +x /opt/app/scripts/ssm_deploy.sh",
              "/opt/app/scripts/ssm_deploy.sh ${{ env.ARTIFACT_BUCKET }} releases/${{ env.ZIP_NAME }}"
            ]' \
            --output text
